Import Library


In [300]:
import numpy as np


Function untuk Gaussian Elimination (No 1)


In [301]:
def GaussianElimination(i, j):
    # Length dari ada berapa persamaan, 3 persamaan = 3 variabel yang berbeda (x1, x2, x3)
    x = len(i)
    # Forward Elimination
    # Jika ada tiga persamaan, maka 2 kali iterate. Maka kita akan iterate sebanyak n-1 persamaan
    for n in range(0, x-1):
        # Setiap iterate, kita akan menghitung dan eliminasi bawahnya sehingga mendapatkan persamaan tunggal (paling bawah)
        for m in range(n+1, x):
            if i[m, n] != 0:
                # Mencari pembagi nya
                multip = i[m, n] / i[n, n]
                # X1, X2, X3, ..... Xn dihitung berdasarkan pembagian.
                i[m, n + 1:x] = i[m, n+1:x] - multip * i[n, n+1:x]
                # Konstanta dari setiap persamaan
                j[m] = j[m]-multip * j[n]
    # Back Substitution
    # Kita iterasi dari belakang, sampai 0
    for n in range(x-1, -1, -1):
        j[n] = (j[n] - np.dot(i[n, n+1:x], j[n+1:x])) / i[n, n]
    return j


Declare Matriks yang diketahui dan Memanggil Function untuk no 1


In [302]:
# Menggunakan Float agar mendapatkan koma di belakang angka.
i = np.array([[3, -1, 4],
              [17, 2, 1],
              [1, 12, -7]],
             float)
j = np.array([2, 14, 54],
             float)

pembuktian = np.linalg.solve(i, j)
hasilNo1 = GaussianElimination(i, j)
print("Hasil no 1 : ")
print(hasilNo1)
print("Pembuktian no 1: ")
print(pembuktian)


Hasil no 1 : 
[0.05901639 5.57377049 1.84918033]
Pembuktian no 1: 
[0.05901639 5.57377049 1.84918033]


Function untuk Gauss-Jordan Elimination (No 2)


In [303]:
def GaussJordanElimination(i):
    # Length dari ada berapa persamaan, 3 persamaan = 3 variabel yang berbeda (x1, x2, x3)
    x = len(i)
    # Iterate sebanyak n + 1 kali karena konstanta dimasukkan menjadi satu matriks
    for n in range(x):
        # Kita ambil pivot yaitu diagonal utama kita.
        # Dan jadikan diagonal utama kita menjadi 1, lalu bagi
        # dengan setiap koefisien di setiap persamaan.
        pivot = i[n, n]
        i[n] = i[n] / pivot

        # Kita iterasi lagi sebanyak n + 1 kali, lalu kita 0 kan
        # Selain dari diagonal utama persamaan tersebut.
        for m in range(x):
            # Jika di matriks diagonal
            if m == n:
                continue
            else:
                # Mencari pembaginya
                multip = i[m, n]
                for o in range(n, x+1):
                    # Jadikan 0 selain diagonal utama
                    i[m, o] = i[m, o] - multip * i[n, o]

    # Buat Array baru yang berisi dari hasil / konstanta persamaan
    # Ambil hanya index terakhir dari setiap persamaan
    # Kenapa x? karena ada 3 persamaan, maka ada 3 variabel
    # Lalu kita ambil saja index ke 3, karena index ke 3 adalah
    # element ke 4, yaitu konstantanya.
    # Maka ambil dari length dari matriks tersebut.
    z = np.array(i[:, x])
    return z


Declare Matriks yang diketahui dan Memanggil Function untuk no 2


In [304]:
# Menggunakan Float agar mendapatkan koma di belakang angka.
i = np.array([[3, -1, 4, 2],
              [17, 2, 1, 14],
              [1, 12, -7, 54]],
             float)
hasilNo2 = GaussJordanElimination(i)
print("Hasil no 2 : ")
print(hasilNo2)
print("Matriks persamaan sekarang:")
print(i)


Hasil no 2 : 
[0.05901639 5.57377049 1.84918033]
Matriks persamaan sekarang:
[[1.         0.         0.         0.05901639]
 [0.         1.         0.         5.57377049]
 [0.         0.         1.         1.84918033]]


Nomber 3


In [305]:
# Menggunakan Algoritma Doolittle
def LU(i):
    x = len(i)
    L = np.identity(x)
    U = np.zeros_like(i)

    for n in range(x):
        L[n, n] = 1
        U[n, n] = (i[n, n] - np.dot(L[n, :n], U[:n, n])) / L[n, n]
        for m in range(n + 1, x):
            U[n, m] = (i[n, m] - np.dot(L[n, :n], U[:n, m])) / L[n, n]
        for o in range(n + 1, x):
            L[o, n] = (i[o, n] - np.dot(L[o, :n], U[:n, n])) / U[n, n]

    return L, U


In [306]:
import scipy.linalg

i = np.array([[3, -1, 4],
              [17, 2, 1],
              [1, 12, -7]],
             float)

L, U = LU(i)
print("Matriks L")
print(L)
print("Matriks U")
print(U)


Matriks L
[[1.         0.         0.        ]
 [5.66666667 1.         0.        ]
 [0.33333333 1.60869565 1.        ]]
Matriks U
[[  3.          -1.           4.        ]
 [  0.           7.66666667 -21.66666667]
 [  0.           0.          26.52173913]]
